/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulador;

import java.awt.HeadlessException;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.swing.JOptionPane;
import static simulador.Cuadrados_Medios_1.buscar;
import simulador.pruebas.ChiCuadrado;
import simulador.pruebas.KolmogorovPrueba;
import simulador.pruebas.Promedios;
import simulador.pruebas.Varianza;

/**
 *
 * @author Administrator
 */
public class SimuladorFunciones extends javax.swing.JFrame {

    private List<Double> aleatorios_generados;

    /**
     * Creates new form SimuladorFunciones
     */
    public SimuladorFunciones() {
	initComponents();
	aleatorios_generados = new ArrayList<Double>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtX = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIteraciones = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtG = new javax.swing.JTextField();
        btGenerar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIteracionesMedios = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtX_GCL = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIteraciones_GCL = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtB = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtM = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        fibN0 = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        cmbOperacion = new javax.swing.JComboBox<>();
        fibN1 = new javax.swing.JSpinner();
        jLabel27 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        fibR = new javax.swing.JSpinner();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        fibM = new javax.swing.JSpinner();
        jLabel36 = new javax.swing.JLabel();
        fibS = new javax.swing.JSpinner();
        jLabel37 = new javax.swing.JLabel();
        fibN = new javax.swing.JSpinner();
        jPanel8 = new javax.swing.JPanel();
        WichX = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        WichY = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        WichZ = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        WichB = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        WichC = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        WichA = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        WichE = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        WichF = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        WichD = new javax.swing.JSpinner();
        WichIter = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        EcuyerY = new javax.swing.JSpinner();
        EcuyerM2 = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        EcuyerM3 = new javax.swing.JSpinner();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        EcuyerM1 = new javax.swing.JSpinner();
        EcuyerB = new javax.swing.JSpinner();
        EcuyerIter = new javax.swing.JSpinner();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        EcuyerX = new javax.swing.JSpinner();
        EcuyerA = new javax.swing.JSpinner();
        jPanel10 = new javax.swing.JPanel();
        cmbTipoPrueba = new javax.swing.JComboBox<>();
        btnPrueba = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        jPanel4.setLayout(new java.awt.GridLayout(2, 4));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Semilla");
        jPanel4.add(jLabel1);

        txtX.setText("1");
        txtX.setToolTipText("");
        jPanel4.add(txtX);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("N° Iteraciones");
        jPanel4.add(jLabel2);

        txtIteraciones.setText("5");
        txtIteraciones.setToolTipText("");
        jPanel4.add(txtIteraciones);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("f(x)=");
        jPanel4.add(jLabel3);

        txtF.setText("(x+2)/x^2");
        txtF.setToolTipText("");
        jPanel4.add(txtF);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("g(x)=");
        jPanel4.add(jLabel4);

        txtG.setText("x*33");
        txtG.setToolTipText("");
        jPanel4.add(txtG);

        btGenerar.setText("Generar");
        btGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btGenerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btGenerar)
                .addGap(14, 14, 14))
        );

        jTabbedPane1.addTab("Basico", jPanel1);

        jPanel5.setLayout(new java.awt.GridLayout(1, 4));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Semilla");
        jPanel5.add(jLabel5);

        txtNumero.setText("1234");
        txtNumero.setToolTipText("");
        jPanel5.add(txtNumero);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("N° Iteraciones");
        jPanel5.add(jLabel6);

        txtIteracionesMedios.setText("5");
        txtIteracionesMedios.setToolTipText("");
        jPanel5.add(txtIteracionesMedios);

        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(67, 67, 67))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(96, 96, 96)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(163, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Medios", null, jPanel2, "");

        jPanel6.setLayout(new java.awt.GridLayout(3, 4));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Semilla");
        jPanel6.add(jLabel7);

        txtX_GCL.setText("1");
        txtX_GCL.setToolTipText("");
        jPanel6.add(txtX_GCL);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("N° Iteraciones");
        jPanel6.add(jLabel8);

        txtIteraciones_GCL.setText("5");
        txtIteraciones_GCL.setToolTipText("");
        jPanel6.add(txtIteraciones_GCL);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("a");
        jPanel6.add(jLabel9);

        txtA.setText("7");
        txtA.setToolTipText("");
        jPanel6.add(txtA);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("b");
        jPanel6.add(jLabel10);

        txtB.setText("5");
        txtB.setToolTipText("");
        jPanel6.add(txtB);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("m");
        jPanel6.add(jLabel11);

        txtM.setText("101");
        txtM.setToolTipText("");
        jPanel6.add(txtM);

        jButton2.setText("Generar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(81, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(46, 46, 46))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(96, 96, 96)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(118, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("GCL", jPanel3);

        jButton3.setText("Hallar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        fibN0.setModel(new javax.swing.SpinnerNumberModel(2, 1, null, 1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Fibonacci");
        jLabel12.setToolTipText("");

        cmbOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "*" }));

        fibN1.setModel(new javax.swing.SpinnerNumberModel(3, 1, null, 1));

        jLabel27.setText("No");

        jLabel32.setText("N1");

        jLabel33.setText("o");

        fibR.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel34.setText("r");

        jLabel35.setText("m");

        fibM.setModel(new javax.swing.SpinnerNumberModel(6, 1, null, 1));

        jLabel36.setText("s");

        fibS.setModel(new javax.swing.SpinnerNumberModel(2, 1, null, 1));

        jLabel37.setText("n");

        fibN.setModel(new javax.swing.SpinnerNumberModel(10, 2, null, 1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel32))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fibN1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fibN0, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel33))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fibM, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(cmbOperacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addGap(18, 18, 18)
                        .addComponent(fibN, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel34)
                            .addGap(18, 18, 18)
                            .addComponent(fibR, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel36)
                            .addGap(18, 18, 18)
                            .addComponent(fibS, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(80, 80, 80))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fibN0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fibN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fibN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel37))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fibS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel36)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel33)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fibR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34)
                            .addComponent(fibM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35))))
                .addGap(38, 38, 38)
                .addComponent(jButton3)
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("Fibonacci", jPanel7);

        WichX.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));

        jLabel13.setText("X:");

        WichY.setModel(new javax.swing.SpinnerNumberModel(2, null, null, 1));

        jLabel14.setText("Y:");

        WichZ.setModel(new javax.swing.SpinnerNumberModel(3, null, null, 1));

        jLabel15.setText("Z:");

        jLabel16.setText("a");

        WichB.setModel(new javax.swing.SpinnerNumberModel(172, null, null, 1));

        jLabel17.setText("b");

        WichC.setModel(new javax.swing.SpinnerNumberModel(170, null, null, 1));

        jLabel18.setText("c");

        WichA.setModel(new javax.swing.SpinnerNumberModel(171, null, null, 1));

        jLabel19.setText("d");

        WichE.setModel(new javax.swing.SpinnerNumberModel(30307, null, null, 1));

        jLabel20.setText("e");

        WichF.setModel(new javax.swing.SpinnerNumberModel(30323, null, null, 1));

        jLabel21.setText("f");

        WichD.setModel(new javax.swing.SpinnerNumberModel(30269, null, null, 1));

        WichIter.setModel(new javax.swing.SpinnerNumberModel(10, null, null, 1));

        jLabel22.setText("Iteraciones:");

        jButton4.setText("Generar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(18, 18, 18)
                                    .addComponent(WichB, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addGap(18, 18, 18)
                                    .addComponent(WichA, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(WichC, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(WichZ, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(18, 18, 18)
                                    .addComponent(WichY, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(18, 18, 18)
                                    .addComponent(WichX, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(WichF, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addGap(18, 18, 18)
                                    .addComponent(WichE, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addGap(18, 18, 18)
                                    .addComponent(WichD, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(WichIter, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton4)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WichD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WichE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WichF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WichA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WichB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WichC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WichX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WichY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WichZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addGap(50, 50, 50)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WichIter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jButton4))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Wichmann", jPanel8);

        jLabel23.setText("X:");

        jLabel24.setText("m1");

        EcuyerY.setModel(new javax.swing.SpinnerNumberModel(87647, 1, null, 1));

        EcuyerM2.setModel(new javax.swing.SpinnerNumberModel(2147483399, null, null, 1));

        jLabel25.setText("Y:");

        jLabel26.setText("m2");

        EcuyerM3.setModel(new javax.swing.SpinnerNumberModel(2147483562, null, null, 1));

        jLabel28.setText("m3");

        jLabel29.setText("a");

        EcuyerM1.setModel(new javax.swing.SpinnerNumberModel(2147483563, null, null, 1));

        EcuyerB.setModel(new javax.swing.SpinnerNumberModel(40692, null, null, 1));

        EcuyerIter.setModel(new javax.swing.SpinnerNumberModel(10, null, null, 1));

        jLabel30.setText("b");

        jLabel31.setText("i =");

        jButton5.setText("Generar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        EcuyerX.setModel(new javax.swing.SpinnerNumberModel(61241, 1, null, 1));

        EcuyerA.setModel(new javax.swing.SpinnerNumberModel(40014, null, null, 1));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(18, 18, 18)
                                .addComponent(EcuyerB, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(EcuyerA, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(18, 18, 18)
                                .addComponent(EcuyerY, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(EcuyerX, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel26))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EcuyerM2)
                                    .addComponent(EcuyerM3)))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EcuyerM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EcuyerIter, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton5)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EcuyerM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EcuyerM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EcuyerM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EcuyerA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EcuyerB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EcuyerX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EcuyerY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28)))
                .addGap(50, 50, 50)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EcuyerIter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(jButton5))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("L'Ecuyer", jPanel9);

        cmbTipoPrueba.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prueba de promedios", "Prueba de chicuadrado", "Prueba de varianza", "Prueba de kolmogorov" }));

        btnPrueba.setText("Aplicar Prueba");
        btnPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPruebaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(cmbTipoPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnPrueba)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipoPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrueba))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pruebas", jPanel10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGenerarActionPerformed
	// TODO add your handling code here:
	int semilla, iteraciones;
	String funcionF, funcionG;

	try {
	    semilla = Integer.parseInt(txtX.getText());
	    iteraciones = Integer.parseInt(txtIteraciones.getText());
	    funcionF = txtF.getText().toLowerCase();
	    funcionG = txtG.getText().toLowerCase();

	} catch (Exception e) {
	    JOptionPane.showMessageDialog(rootPane, "Datos ingresador invalidos.\n intente nuevamente.");
	    return;
	}

	double fx = ejecutarFuncion(semilla, funcionF, iteraciones);

	JOptionPane.showMessageDialog(rootPane, String.format("f(x)=%.2f", fx));

	double gx = ejecutarFuncion(semilla, funcionG, iteraciones);

	JOptionPane.showMessageDialog(rootPane, String.format("g(x)=%.2f", gx));
	//JOptionPane.showMessageDialog(rootPane, String.format("f(x)=%.2f\ng(x)=%.2f", fx,gx));


    }//GEN-LAST:event_btGenerarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	// TODO add your handling code here:

	//vacia la lista de aleatorios
	aleatorios_generados.clear();

	BigInteger n = new BigInteger(txtNumero.getText());

	int r = Integer.parseInt(txtIteracionesMedios.getText());
	int aux = 0, digito = String.valueOf(n).length();

	System.out.println("Generador Medios");
	for (int i = 0; i < r; i++) {
	    aux = buscar(n.multiply(n).toString(), digito);

	    n = BigInteger.valueOf(aux);
	    System.out.println("0." + aux);
	    //agrega a la lista el numero
	    aleatorios_generados.add(Double.parseDouble("0." + aux));
	}
	JOptionPane.showMessageDialog(rootPane, "se generaron los numeros\n revise la consola.");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

	//vacia la lista de aleatorios
	aleatorios_generados.clear();

	int a, b, m, x, n;

	try {
	    a = Integer.parseInt(txtA.getText());
	    b = Integer.parseInt(txtB.getText());
	    m = Integer.parseInt(txtM.getText());
	    x = Integer.parseInt(txtX_GCL.getText());
	    n = Integer.parseInt(txtIteraciones_GCL.getText());
	} catch (Exception e) {
	    JOptionPane.showMessageDialog(rootPane, "valores ingresados invalidos.");
	    return;
	}

	System.out.println("GENERADOR LINEAL:");
	for (int i = 0; i < n; i++) {
	    x = ((a * x) + b) % m;
	    double aleatorio = (double) x / m;
	    System.out.println(aleatorio);
	    //agrega el aleatorios a la lista
	    aleatorios_generados.add(aleatorio);

	}

	JOptionPane.showMessageDialog(rootPane, "se generaron los numeros\n revise la consola.");


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
	//vacia la lista de aleatorios
	aleatorios_generados.clear();

	//operacion
	int operacion = cmbOperacion.getSelectedIndex() + 1;

	//valor de n
	int n = (int) fibN.getValue();
	int n0 = (int) fibN0.getValue();
	int n1 = (int) fibN1.getValue();
	int m = (int) fibM.getValue();
	int r = (int) fibR.getValue();
	int s = (int) fibS.getValue();

	if (s == r) {
	    JOptionPane.showMessageDialog(rootPane, "S y R deben ser distintos.");
	    return;
	}
	if (s == n || r == n) {
	    JOptionPane.showMessageDialog(rootPane, "S y R deben ser menores a n.");
	    return;
	}

	//imprime en consola la secuencia
	System.out.println("\n\nFIBONACCI SECUENCIA " + n);

//        for (int i = 1; i <= n; i++) {
//            System.out.println(i + ": " + Fibonacci.fib(i, operacion));
//
//        }
	for (int i = 0; i <= n; i++) {
	    double aleatorio = Double.parseDouble("0." + Fibonacci.fib(i, n0, n1, m, s, r, operacion));
	    System.out.println(aleatorio);
	    //agrega el aleatorios a la lista
	    aleatorios_generados.add(aleatorio);
	}

	JOptionPane.showMessageDialog(rootPane, "se generaron los numeros\n revise la consola.");
	//JOptionPane.showMessageDialog(rootPane,Fibonacci.fib(n,n0,n1, m,s,r,operacion));


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
	//vacia la lista de aleatorios
	aleatorios_generados.clear();

	int a0 = (int) WichA.getValue();
	int a1 = (int) WichB.getValue();
	int a2 = (int) WichC.getValue();
	int b0 = (int) WichD.getValue();
	int b1 = (int) WichE.getValue();
	int b2 = (int) WichF.getValue();
	int x = (int) WichX.getValue();
	int y = (int) WichY.getValue();
	int z = (int) WichZ.getValue();
	int iter = (int) WichIter.getValue();
	double aleatorio = 0.0;
	System.out.println("\n\nWichmann y Hill SECUENCIA \n");
	for (int i = 0; i < iter; i++) {
	    WichmannHill wh = new WichmannHill(a0, a1, a2, b0, b1, b2, x + i, y + i, z + i);
	    aleatorio = wh.random();
	    System.out.println(aleatorio);
	    //agrega el aleatorios a la lista
	    aleatorios_generados.add(aleatorio);
	}
	JOptionPane.showMessageDialog(rootPane, "se generaron los numeros\n revise la consola.");
	//JOptionPane.showMessageDialog(rootPane, aleatorio);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
	//vacia la lista de aleatorios
	aleatorios_generados.clear();

	double a1 = (int) EcuyerA.getValue();
	double a2 = (int) EcuyerB.getValue();
	double m1 = (int) EcuyerM1.getValue();
	double m2 = (int) EcuyerM2.getValue();
	double m3 = (int) EcuyerM3.getValue();
	double x = (int) EcuyerX.getValue();
	double y = (int) EcuyerY.getValue();

	int iter = (int) EcuyerIter.getValue();
	double aleatorio = 0.0;
	System.out.println("\n\nL'Ecuyer SECUENCIA \n");
	for (int i = 0; i <= iter; i++) {
	    L_Ecuyer ecuyer = new L_Ecuyer(a1, a2, m1, m2, m3, x, y, i);
	    aleatorio = ecuyer.random();

	    // System.out.print("U"+i+" = ");
	    System.out.println(aleatorio);
	    //agrega el aleatorios a la lista
	    aleatorios_generados.add(aleatorio);
	}
	JOptionPane.showMessageDialog(rootPane, "se generaron los numeros\n revise la consola.");
	// JOptionPane.showMessageDialog(rootPane, new BigDecimal(aleatorio).toString());

    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPruebaActionPerformed
	// TODO add your handling code here:

	if (aleatorios_generados.isEmpty()) {
	    JOptionPane.showMessageDialog(rootPane, "No se han generado aleatorios\n"
		    + "selecccione algun generador para cargar los numeros");
	    return;
	}

	int index = cmbTipoPrueba.getSelectedIndex();

	if (index == 0) {
	    //Prueba de promedios
	    System.out.println("\nPrueba de promedios");
	    Promedios prueba = new Promedios(aleatorios_generados);
	    boolean paso = prueba.evaluar();
	    if (paso) {
		System.out.println("Los numeros superaron la prueba");
	    } else {
		System.out.println("Los numeros no pasaron la prueba");
	    }

	} else if (index == 1) {
	    //Prueba de Chi Cuadrado
	    System.out.println("\nPrueba de Chi Cuadrado:");
	    ChiCuadrado prueba = new ChiCuadrado(aleatorios_generados);
	    prueba.evaluar();
	} else if (index == 2) {
	    //Prueba de varianza
	    System.out.println("\nPrueba de varianza");
	    Varianza prueba = new Varianza(aleatorios_generados);
	    prueba.evaluar();

	} else if (index == 3) {
	    //Prueba de Kolmogorov
	    System.out.println("\nPrueba de Kolmogorov");
	    KolmogorovPrueba oKolmogorov = new KolmogorovPrueba(aleatorios_generados);
	    oKolmogorov.setiAlfa(1);

	    oKolmogorov.calcularFn();

	    double valorDn = oKolmogorov.calcularDn();
	    double[][] fResultado = oKolmogorov.getMatrizFrecuencia();

	    System.out.println(" Xi\tFn(Xi)\tDif");

	    for (int i = 0; i < fResultado.length; i++) {
		for (int j = 0; j < 3; j++) {
		    System.out.print(String.valueOf(fResultado[i][j]) + "\t");
		}
		System.out.println();
	    }
	    if (oKolmogorov.isPasaPrueba()) {

		System.out.println("D = " + valorDn + "\n alfa = " + oKolmogorov.getFinalAlfa() + " \nSi pasa la prueba de Kolmogorov");
		System.out.println("Pasala prueba");

	    } else {

		System.out.println("D = " + valorDn + "\n alfa = " + oKolmogorov.getFinalAlfa() + " \nNo pasa la prueba de Kolmogorov");
		System.out.println("No Pasala prueba");
	    }

	}


    }//GEN-LAST:event_btnPruebaActionPerformed

    private double ejecutarFuncion(int semilla, String funcion, int iteraciones) throws HeadlessException {
	double x = semilla;
	//quita cualquier espacion en la funcion
	funcion = funcion.replace("\\s+", "");
	//utiliza libreria JAVASCRIPT para ejecutar las operaciones
	ScriptEngineManager mgr = new ScriptEngineManager();
	ScriptEngine engine = mgr.getEngineByName("JavaScript");

	try {

	    for (int i = 0; i < iteraciones; i++) {

		String temp = funcion.replace("x", String.format("%.2f", x));
		System.out.print("funcion = " + temp + " = ");

		//busca potencias
		while (temp.indexOf("^") != -1) {
		    int index = temp.indexOf("^");
		    String base = "";
		    String potencia = "";
		    int j = index + 1;

		    while (j < temp.length() && (Character.isDigit(temp.charAt(j)) || temp.charAt(j) == '.')) {
			potencia += temp.charAt(j);
			j++;
		    }

		    j = index - 1;
		    while (j >= 0 && (Character.isDigit(temp.charAt(j)) || temp.charAt(j) == '.')) {
			base = temp.charAt(j) + base;
			j--;
		    }

		    //System.out.println(base+"^"+potencia);
		    //obtiene el valor de la potencia
		    double s_resultado = Math.pow(Double.parseDouble(base), Double.parseDouble(potencia));
		    //reemplaza base a la potencia por el real valor numerico
		    temp = temp.replace(base + "^" + potencia, String.format("%.2f", s_resultado));
		    System.out.println(temp);
		}

		//evalua la ecuacion
		x = (double) engine.eval(temp);
		System.out.println(String.format("%.2f", x));

	    }
	} catch (Exception e) {
	    JOptionPane.showMessageDialog(rootPane, "se ha presentado un error al aplicar la formula");
	    System.out.println(e.getCause());
	    System.out.println(e.getMessage());
	}
	return x;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(SimuladorFunciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(SimuladorFunciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(SimuladorFunciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(SimuladorFunciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new SimuladorFunciones().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner EcuyerA;
    private javax.swing.JSpinner EcuyerB;
    private javax.swing.JSpinner EcuyerIter;
    private javax.swing.JSpinner EcuyerM1;
    private javax.swing.JSpinner EcuyerM2;
    private javax.swing.JSpinner EcuyerM3;
    private javax.swing.JSpinner EcuyerX;
    private javax.swing.JSpinner EcuyerY;
    private javax.swing.JSpinner WichA;
    private javax.swing.JSpinner WichB;
    private javax.swing.JSpinner WichC;
    private javax.swing.JSpinner WichD;
    private javax.swing.JSpinner WichE;
    private javax.swing.JSpinner WichF;
    private javax.swing.JSpinner WichIter;
    private javax.swing.JSpinner WichX;
    private javax.swing.JSpinner WichY;
    private javax.swing.JSpinner WichZ;
    private javax.swing.JButton btGenerar;
    private javax.swing.JButton btnPrueba;
    private javax.swing.JComboBox<String> cmbOperacion;
    private javax.swing.JComboBox<String> cmbTipoPrueba;
    private javax.swing.JSpinner fibM;
    private javax.swing.JSpinner fibN;
    private javax.swing.JSpinner fibN0;
    private javax.swing.JSpinner fibN1;
    private javax.swing.JSpinner fibR;
    private javax.swing.JSpinner fibS;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtF;
    private javax.swing.JTextField txtG;
    private javax.swing.JTextField txtIteraciones;
    private javax.swing.JTextField txtIteracionesMedios;
    private javax.swing.JTextField txtIteraciones_GCL;
    private javax.swing.JTextField txtM;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtX;
    private javax.swing.JTextField txtX_GCL;
    // End of variables declaration//GEN-END:variables

}
